Vagrant.configure("2") do |config|

  config.vm.define "srv-web" do |web|
    web.vm.box = "ubuntu/focal64"
    web.vm.hostname = "srv-web"
    web.vm.network "private_network", ip: "192.168.56.40"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

end