Vagrant.configure("2") do |config|

  config.vm.define "srv-app" do |app|
    app.vm.box = "ubuntu/focal64"
    app.vm.hostname = "srv-app"
    app.vm.network "private_network", ip: "192.168.56.10"
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "srv-db" do |db|
    db.vm.box = "ubuntu/focal64"
    db.vm.hostname = "srv-db"
    db.vm.network "private_network", ip: "192.168.56.20"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

end