Vagrant.configure("2") do |config|

  config.vm.define "server-back" do |back|
    back.vm.box = "ubuntu/focal64"
    back.vm.hostname = "server-back"
    back.vm.network "private_network", ip: "192.168.56.30"
    back.vm.provider "virtualbox" do |vb|
      vb.memory = "1512"
      vb.cpus = 2
    end
  end

  config.vm.define "server-dba" do |dba|
    dba.vm.box = "ubuntu/focal64"
    dba.vm.hostname = "server-dba"
    dba.vm.network "private_network", ip: "192.168.56.31"
    dba.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  config.vm.define "server-front" do |front|
    front.vm.box = "ubuntu/focal64"
    front.vm.hostname = "server-front"
    front.vm.network "private_network", ip: "192.168.56.32"
    front.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
  end


   config.vm.define "server-jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/focal64"
    jenkins.vm.hostname = "server-jenkins"
    jenkins.vm.boot_timeout = 600
    jenkins.vm.network "private_network", ip: "192.168.56.33"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 9090
    jenkins.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

end